import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();
export const useLanguage = () => useContext(LanguageContext);

const translations = {
  en: {
    home: "Home",
    offers: "Limited Offers",
    myOrders: "My Orders",
    trackOrder: "Track Order",
    trackOrderBtn: "Track Order",
    cart: "Cart",
    login: "Login",
    signup: "Sign Up",
    logout: "Logout",
    support: "Support",
    allProducts: "All Products",
    flashSale: "Flash Sale",
    todaysDeals: "Today's Deals",
    trendingProducts: "Trending Products",
    filters: "Filters",
    pongalSale: "Pongal Sale - Up to 30% OFF on Traditional Tamil Rice",
    freeDelivery: "Free Delivery Above ₹500",
    freeDeliveryOnOrders: "Free Delivery on orders above ₹500!",
    marketPrice: "Market",
    stable: "stable",
    alreadyPremium: "Already premium",
    premiumDiscount: "10% premium",
    premiumMember: "Premium member",
    premiumDiscountApplied: "Premium discount applied",
    premium: "Premium",
    premiumSavings: "Premium savings",
    searchRiceProducts: "Search rice products",
    categories: "Categories",
    clearAllFilters: "Clear All Filters",
    searchRice: "Search rice",
    priceRange: "Price range (per kg)",
    allPrices: "All prices",
    riceColor: "Rice color",
    riceType: "Rice type",
    discoverCollection: "Discover our complete collection of premium rice varieties",
    limitedTimeHugeDiscounts: "Limited time with huge discounts!",
    limitedOffersExtraDiscounts: "Limited offers with extra discounts!",
    liveMarketPrice: "Live market price",
    totalPrice: "Total price",
    easyToDigest: "Easy to digest",
    goodForDailyMeals: "Good for daily meals",
    provideLongLastingEnergy: "Provide long lasting energy",
    lowFat: "Low fat",
    location: "Location",
    chennai: "Chennai",
    freeDeliveryWithin: "Free delivery within 3-5 days",
    shipsFrom: "Ships from: vetri vinayagar Rice mart",
    orderBefore6pm: "Order before 6 pm for next day processing",
    returnPolicy: "Return policy",
    dayReturnPolicy: "7 day return policy",
    damagedProductReplacement: "Damaged product replacement",
    noQuestionsAsked: "No questions asked",
    fullRefundAvailable: "Full refund available",
    helpsControlBloodSugar: "Helps control blood sugar",
    richInFiber: "Rich in fiber",
    goodForHeartHealth: "Good for heart health",
    helpsDigestion: "Helps digestion",
    veryHighAntioxidants: "Very high antioxidants",
    improvesImmunity: "Improves immunity",
    richIron: "Rich iron",
    goodForBones: "Good for bones",
    increasesBodyStrength: "Increases body strength",
    detoxifiesBody: "Detoxifies body",
    boostsImmunity: "Boots immunity",
    improvesMetabolism: "Improves metabolism",
    glutenFree: "Gluten free",
    goodEnergySource: "Good energy source",
    easyDigestion: "Easy digestion",
    highFiber: "High fiber",
    helpsWeightControl: "Helps weight control",
    supportsGutHealth: "Supports gut health",
    richInMinerals: "Rich in minerals",
    goodForWomensHealth: "Good for women's health",
    strengthensImmunity: "Strengthens immunity",
    naturalAntioxidants: "Natural antioxidants",
    aromaticTraditionalRice: "Aromatic traditional rice",
    lowGlycemicIndex: "Low glycemic index",
    richInNutrients: "Rich in nutrients",
    highIronContent: "High iron content",
    supportsWeightLoss: "Supports weight loss",
    addedToCart: "Added to cart",
    dealFixed: "Deal fixed",
    youSave: "You save",
    grabSpecialComboDeals: "Grab special combo deals - today only",
    viewCombo: "View combo",
    limitedOffers: "Limited offers",
    free: "Free",
    freeBonus: "Free bonus",
    mainProduct: "Main product",
    freeProduct: "Free product",
    chooseRiceAge: "Choose rice age",
    monthsAged: "Months Aged",
    yearAged: "1 year aged",
    yearsAged: "2 years aged",
    addComboToCart: "Add combo to cart",
    responseWithin24Hours: "Response within 24 hours",
    chennaiTamilNadu: "Chennai tamil nadu",
    frequentlyAskedQuestions: "Frequently Asked Questions",
    whatIsDeliveryTime: "What is the delivery time?",
    standardDeliveryTakes: "Standard delivery takes 3-5 business days. Express delivery available in select areas.",
    doYouAcceptReturns: "Do you accept returns?",
    yesWeOffer7DayReturn: "Yes, we offer 7-day return policy for damaged or defective products.",
    whatPaymentMethods: "What payment methods do you accept?",
    weAcceptCashOnDelivery: "We accept Cash on Delivery, UPI, Credit/Debit Cards, and Net Banking.",
    howCanITrackOrder: "How can I track my order?",
    youCanTrackOrder: "You can track your order using the Order ID on our Track Order page.",
    orderId: "Order ID",
    delivered: "Delivered",
    placed: "Placed",
    shipped: "Shipped",
    processing: "Processing",
    buyAgain: "Buy again",
    rateProduct: "Rate",
    returnProduct: "Return",
    status: "Status",
    payment: "Payment",
    date: "Date",
    items: "Items",
    close: "Close",
    pleaseSelectReasonForReturn: "Please select a reason for return",
    damagedProduct: "Damaged product",
    wrongItemDelivered: "Wrong item delivered",
    qualityNotAsExpected: "Quality not as expected",
    sizeFitIssue: "Size/fit issue",
    other: "Other",
    additionalDetailsOptional: "Additional details (optional)",
    submitReturn: "Submit return",
    cancel: "Cancel",
    cod: "COD",
    qty: "Qty",
    viewProduct: "View Product",
    healthBenefits: "Health Benefits",
    rating: "Rating",
    selectAge: "Select Age",
    selectWeight: "Select Weight",
    quantity: "Quantity",
    addToCart: "Add to Cart",
    buyNow: "Buy Now",
    type: "Type",
    color: "Color",
    deliveryInfo: "Delivery Information",
    returnPolicy: "Return Policy",
    yourCart: "Your Cart",
    continueShopping: "Continue Shopping",
    proceedToCheckout: "Proceed to Checkout",
    viewCart: "View Cart",
    checkout: "Checkout",
    orderSummary: "Order Summary",
    paymentMethod: "Payment Method",
    cashOnDelivery: "Cash on Delivery",
    creditDebitCard: "Credit / Debit Card",
    customerSupport: "Customer Support",
    phoneSupport: "Phone Support",
    emailSupport: "Email Support",
    visitUs: "Visit Us",
    price: "Price",
    total: "Total",
    discount: "Discount",
    off: "OFF",
    kg: "kg",
    left: "left",
    orderSoon: "Order soon!",
    available: "Available",
    aged: "Aged",
    trending: "Trending",
    trendingProduct: "Trending Product",
    weight: "Weight",
    age: "Age",
    year: "year",
    years: "years",
    months: "months",
    extraOff: "EXTRA OFF",
    todaysDeal: "TODAY'S DEAL",
    mostPopularRice: "Most popular rice varieties this week",
    joinNow: "Join Now",
    freeDelivery2: "Free delivery",
    earlyAccess: "Early access to sales",
    discountOnAllRice: "discount on all rice",
    riceMartPremium: "Rice Mart Premium",
    "Easy to digest": "Easy to digest",
    "Good for daily meals": "Good for daily meals",
    "Provides long lasting energy": "Provides long lasting energy",
    "Low fat": "Low fat",
    "Helps control blood sugar": "Helps control blood sugar",
    "Rich in fiber": "Rich in fiber",
    "Good for heart health": "Good for heart health",
    "Helps digestion": "Helps digestion",
    "Very high antioxidants": "Very high antioxidants",
    "Improves immunity": "Improves immunity",
    "Rich in iron": "Rich in iron",
    "Increases body strength": "Increases body strength",
    "Good for bones": "Good for bones",
    "Improves stamina": "Improves stamina",
    "Detoxifies body": "Detoxifies body",
    "Boosts immunity": "Boosts immunity",
    "Improves metabolism": "Improves metabolism",
    "Gluten free": "Gluten free",
    "Easy digestion": "Easy digestion",
    "Good energy source": "Good energy source",
    "High fiber": "High fiber",
    "Helps weight control": "Helps weight control",
    "Supports gut health": "Supports gut health",
    "Rich in minerals": "Rich in minerals",
    "Good for women's health": "Good for women's health",
    "Strengthens immunity": "Strengthens immunity",
    "Natural antioxidants": "Natural antioxidants",
    "Aromatic traditional rice": "Aromatic traditional rice",
    "Low glycemic index": "Low glycemic index",
    "Rich in nutrients": "Rich in nutrients",
    "High iron content": "High iron content",
    "Supports weight loss": "Supports weight loss",
    "Premium Quality": "Premium Quality",
    email: "Email",
    password: "Password",
    confirmPassword: "Confirm Password",
    fullName: "Full Name",
    signIn: "Sign In",
    createAccount: "Create Account",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    forgotPassword: "Forgot Password?",
    showPassword: "Show Password",
    hidePassword: "Hide Password",
    emptyCart: "Your cart is empty",
    removeFromCart: "Remove from Cart",
    updateQuantity: "Update Quantity",
    subtotal: "Subtotal",
    productDetails: "Product Details",
    specifications: "Specifications",
    reviews: "Reviews",
    relatedProducts: "Related Products",
    outOfStock: "Out of Stock",
    inStock: "In Stock",
    orderHistory: "Order History",
    orderNumber: "Order Number",
    orderDate: "Order Date",
    orderStatus: "Order Status",
    orderTotal: "Order Total",
    viewDetails: "View Details",
    contactUs: "Contact Us",
    getInTouch: "Get in Touch",
    address: "Address",
    phone: "Phone",
    enterOrderNumber: "Enter Order Number",
    trackYourOrder: "Track Your Order",
    orderNotFound: "Order Not Found",
    limitedTimeOffers: "Limited Time Offers",
    offerExpires: "Offer Expires",
    orderPlaced: "Order Placed Successfully",
    thankYou: "Thank You",
    orderConfirmation: "Order Confirmation",
    Traditional: "Traditional",
    Premium: "Premium",
    Aromatic: "Aromatic",
    White: "White",
    Red: "Red",
    Black: "Black",
    Brown: "Brown",
    "Basmati Rice": "Basmati Rice",
    "Seeraga Samba Rice": "Seeraga Samba Rice",
    "Karuppu Kavuni Rice": "Karuppu Kavuni Rice",
    "Ponni Rice": "Ponni Rice",
    "Idly Rice": "Idly Rice",
    "Mappillai Samba Rice": "Mappillai Samba Rice",
    "Kattuyanam Rice": "Kattuyanam Rice",
    "Thooyamalli Rice": "Thooyamalli Rice",
    "Nei Kichadi Rice": "Nei Kichadi Rice",
    "Karunguruvai Rice": "Karunguruvai Rice",
    "Poongar Rice": "Poongar Rice",
    "Red Rice": "Red Rice"
  },
  ta: {
    home: "முகப்பு",
    offers: "சிறப்பு சலுகைகள்",
    myOrders: "என் ஆர்டர்கள்",
    trackOrder: "ஆர்டர் கண்காணிப்பு",
    trackOrderBtn: "ஆர்டர் கண்காணி",
    cart: "கார்ட்",
    login: "உள்நுழைவு",
    signup: "பதிவு செய்யவும்",
    logout: "வெளியேறு",
    support: "ஆதரவு",
    allProducts: "அனைத்து பொருட்கள்",
    flashSale: "ஃப்ளாஷ் சேல்",
    todaysDeals: "இன்றைய சலுகைகள்",
    trendingProducts: "டிரெண்டிங் பொருட்கள்",
    filters: "வடிகட்டிகள்",
    pongalSale: "பொங்கல் விற்பனை - பாரம்பரிய தமிழ் அரிசியில் 30% வரை தள்ளுபடி",
    freeDelivery: "₹500க்கு மேல் இலவச டெலிவரி",
    freeDeliveryOnOrders: "₹500க்கு மேல் ஆர்டர்களில் இலவச டெலிவரி!📊",
    marketPrice: "சந்தை",
    stable: "நிலையான",
    alreadyPremium: "ஏற்கனவே பிரீமியம்",
    premiumDiscount: "10% பிரீமியம்",
    premiumMember: "பிரீமியம் உறுப்பினர்",
    premiumDiscountApplied: "பிரீமியம் தள்ளுபடி பயன்படுத்தப்பட்டது",
    premium: "பிரீமியம்",
    premiumSavings: "பிரீமியம் சேமிப்பு",
    searchRiceProducts: "அரிசி பொருட்களை தேடவும்",
    categories: "வகைகள்",
    clearAllFilters: "அனைத்து வடிகட்டிகளையும் அழிக்கவும்",
    searchRice: "அரிசி தேடவும்",
    priceRange: "விலை வரம்பு (கிலோவிற்கு)",
    allPrices: "அனைத்து விலைகள்",
    riceColor: "அரிசி நிறம்",
    riceType: "அரிசி வகை",
    discoverCollection: "எங்களின் முழுமையான பிரீமியம் அரிசி வகைகளின் தொகுப்பை கண்டுபிடிக்கவும்",
    limitedTimeHugeDiscounts: "குறிப்பிட்ட காலம் பெரிய தள்ளுபடிகளுடன்!",
    limitedOffersExtraDiscounts: "குறிப்பிட்ட சலுகைகள் கூடுதல் தள்ளுபடிகளுடன்!",
    liveMarketPrice: "நேரடி சந்தை விலை",
    totalPrice: "முழு விலை",
    easyToDigest: "எளிதில் ஜீரணமாகும்",
    goodForDailyMeals: "தினசரி உணவுக்கு நல்லது",
    provideLongLastingEnergy: "நீண்ட கால சக்தி அளிக்கும்",
    lowFat: "குறைந்த கொழுப்பு",
    location: "இடம்",
    chennai: "சென்னை",
    freeDeliveryWithin: "3-5 நாட்களில் இலவச டெலிவரி",
    shipsFrom: "அனுப்புகிறது: வேத்ரி விநாயகர் ரைச் மார்ட்",
    orderBefore6pm: "அடுத்த நாள் செயல்பாடுக்காக மாலை 6 மணிக்கு முன் ஆர்டர் செய்யவும்",
    dayReturnPolicy: "7 நாள் திரும்ப கொடுக்கும் கொள்கை",
    damagedProductReplacement: "சேதமடைந்த பொருள் மாற்றுதல்",
    noQuestionsAsked: "கேள்விகள் இல்லை",
    fullRefundAvailable: "முழு பணம் திரும்ப கிடைக்கும்",
    helpsControlBloodSugar: "இரத்த சர்க்கரையை கட்டுப்படுத்த உதவும்",
    richInFiber: "நார்ச்சத்து நிறைந்தது",
    goodForHeartHealth: "இதய ஆரோக்கியத்திற்கு நல்லது",
    helpsDigestion: "ஜீரணத்திற்கு உதவும்",
    veryHighAntioxidants: "மிக அதிக ஆன்டிஆக்சிடன்ட்கள்",
    improvesImmunity: "நோய் எதிர்ப்பு சக்தியை மேம்படுத்தும்",
    richIron: "இரும்புச்சத்து நிறைந்தது",
    goodForBones: "எலும்புகளுக்கு நல்லது",
    increasesBodyStrength: "உடல் வலிமையை அதிகரிக்கும்",
    detoxifiesBody: "உடலை நச்சுத்தன்மையாக்கும்",
    boostsImmunity: "நோய் எதிர்ப்பு சக்தியை அதிகரிக்கும்",
    improvesMetabolism: "வளர்சிதை மாற்றத்தை மேம்படுத்தும்",
    glutenFree: "குளூடன் இல்லாதது",
    goodEnergySource: "நல்ல சக்தி மூலம்",
    easyDigestion: "எளிய ஜீரணம்",
    highFiber: "அதிக நார்ச்சத்து",
    helpsWeightControl: "எடை கட்டுப்பாட்டிற்கு உதவும்",
    supportsGutHealth: "குடல் ஆரோக்கியத்தை ஆதரிக்கும்",
    richInMinerals: "கனிமங்கள் நிறைந்தது",
    goodForWomensHealth: "பெண்களின் ஆரோக்கியத்திற்கு நல்லது",
    strengthensImmunity: "நோய் எதிர்ப்பு சக்தியை வலுப்படுத்தும்",
    naturalAntioxidants: "இயற்கை ஆன்டிஆக்சிடன்ட்கள்",
    aromaticTraditionalRice: "நறுமணமுள்ள பாரம்பரிய அரிசி",
    lowGlycemicIndex: "குறைந்த கிளைசெமிக் குறியீடு",
    richInNutrients: "ஊட்டச்சத்துக்கள் நிறைந்தது",
    highIronContent: "அதிக இரும்புச்சத்து",
    supportsWeightLoss: "எடை குறைப்பிற்கு உதவும்",
    addedToCart: "கார்ட்டில் சேர்க்கப்பட்டது",
    dealFixed: "சலுகை நிர்ணயிக்கப்பட்டது",
    youSave: "நீங்கள் சேமிக்கிறீர்கள்",
    grabSpecialComboDeals: "சிறப்பு கூட்டு சலுகைகளை பெறுங்கள் - இன்று மட்டும்",
    viewCombo: "கூட்டு பார்க்கவும்",
    limitedOffers: "குறிப்பிட்ட சலுகைகள்",
    free: "இலவசம்",
    freeBonus: "இலவச போனஸ்",
    mainProduct: "முக்கிய பொருள்",
    freeProduct: "இலவச பொருள்",
    chooseRiceAge: "அரிசி வயதை தேர்ந்தெடுக்கவும்",
    monthsAged: "மாதங்கள் பழைமையான",
    yearAged: "1 வருடம் பழைமையான",
    yearsAged: "2 வருடங்கள் பழைமையான",
    addComboToCart: "கூட்டு கார்ட்டில் சேர்க்கவும்",
    responseWithin24Hours: "24 மணி நேரத்திற்குள் பதில்",
    chennaiTamilNadu: "சென்னை தமிழ்நாடு",
    frequentlyAskedQuestions: "அடிக்கடி கேட்கப்படும் கேள்விகள்",
    whatIsDeliveryTime: "டெலிவரி நேரம் என்ன?",
    standardDeliveryTakes: "நிலையான டெலிவரி 3-5 வணிக நாட்கள் எடுக்கும். தேர்ந்தெடுக்கப்பட்ட பகுதிகளில் எக்ஸ்பிரஸ் டெலிவரி கிடைக்கும்.",
    doYouAcceptReturns: "நீங்கள் திரும்பப் பெறுவதை ஏற்றுக்கொள்கிறீர்களா?",
    yesWeOffer7DayReturn: "ஆம், சேதமடைந்த அல்லது குறைபாடுள்ள பொருட்களுக்கு 7 நாள் திரும்பப் பெறும் கொள்கையை வழங்குகிறோம்.",
    whatPaymentMethods: "நீங்கள் என்ன பணம் செலுத்தும் முறைகளை ஏற்றுக்கொள்கிறீர்கள்?",
    weAcceptCashOnDelivery: "நாங்கள் பணம் வாங்கும்போது கொடுக்கும், UPI, கிரெடிட்/டெபிட் கார்டுகள் மற்றும் நெட் பேங்கிங் ஏற்றுக்கொள்கிறோம்.",
    howCanITrackOrder: "நான் எப்படி என் ஆர்டரை கண்காணிக்க முடியும்?",
    youCanTrackOrder: "எங்கள் ட்ராக் ஆர்டர் பக்கத்தில் ஆர்டர் ஐடியைப் பயன்படுத்தி உங்கள் ஆர்டரை கண்காணிக்கலாம்.",
    orderId: "ஆர்டர் ஐடி",
    delivered: "டெலிவர் செய்யப்பட்டது",
    placed: "வைக்கப்பட்டது",
    shipped: "அனுப்பப்பட்டது",
    processing: "செயலாக்கம்",
    buyAgain: "மீண்டும் வாங்கவும்",
    rateProduct: "மதிப்பிடவும்",
    returnProduct: "திரும்பப் பெறவும்",
    status: "நிலை",
    payment: "பணம் செலுத்துதல்",
    date: "தேதி",
    items: "பொருட்கள்",
    close: "மூடவும்",
    pleaseSelectReasonForReturn: "திரும்பப் பெறுவதற்கான காரணத்தைத் தேர்ந்தெடுக்கவும்",
    damagedProduct: "சேதமடைந்த பொருள்",
    wrongItemDelivered: "தவறான பொருள் டெலிவர் செய்யப்பட்டது",
    qualityNotAsExpected: "எதிர்பார்த்த தரம் இல்லை",
    sizeFitIssue: "அளவு/பொருத்தம் பிரச்சினை",
    other: "மற்றவை",
    additionalDetailsOptional: "கூடுதல் விவரங்கள் (விருப்பம்)",
    submitReturn: "திரும்பப் பெறுதலை சமர்ப்பிக்கவும்",
    cancel: "ரத்து செய்யவும்",
    cod: "COD",
    qty: "அளவு",
    viewProduct: "பொருளைப் பார்க்கவும்",
    healthBenefits: "ஆரோக்கிய நன்மைகள்",
    rating: "மதிப்பீடு",
    selectAge: "வயதைத் தேர்ந்தெடுக்கவும்",
    selectWeight: "எடையைத் தேர்ந்தெடுக்கவும்",
    quantity: "அளவு",
    addToCart: "கார்ட்டில் சேர்க்கவும்",
    buyNow: "இப்போது வாங்கவும்",
    type: "வகை",
    color: "நிறம்",
    deliveryInfo: "டெலிவரி தகவல்",
    returnPolicy: "திரும்ப கொடுக்கும் கொள்கை",
    yourCart: "உங்கள் கார்ட்",
    continueShopping: "ஷாப்பிங் தொடரவும்",
    proceedToCheckout: "செக்அவுட்டுக்கு செல்லவும்",
    viewCart: "கார்டைப் பார்க்கவும்",
    checkout: "செக்அவுட்",
    orderSummary: "ஆர்டர் சுருக்கம்",
    paymentMethod: "பணம் செலுத்தும் முறை",
    cashOnDelivery: "பணம் வாங்கும்போது கொடுக்கவும்",
    creditDebitCard: "கிரெடிட் / டெபிட் கார்டு",
    customerSupport: "வாடிக்கையாளர் ஆதரவு",
    phoneSupport: "தொலைபேசி ஆதரவு",
    emailSupport: "மின்னஞ்சல் ஆதரவு",
    visitUs: "எங்களைப் பார்வையிடவும்",
    price: "விலை",
    total: "மொத்தம்",
    discount: "தள்ளுபடி",
    off: "தள்ளுபடி",
    kg: "கிலோ",
    left: "மீதம்",
    orderSoon: "விரைவில் ஆர்டர் செய்யவும்!",
    available: "கிடைக்கிறது",
    aged: "பழைமையான",
    trending: "டிரெண்டிங்",
    trendingProduct: "டிரெண்டிங் பொருள்",
    weight: "எடை",
    age: "வயது",
    year: "வருடம்",
    years: "வருடங்கள்",
    months: "மாதங்கள்",
    extraOff: "கூடுதல் தள்ளுபடி",
    todaysDeal: "இன்றைய சலுகை",
    mostPopularRice: "இந்த வாரம் மிகவும் பிரபலமான அரிசி வகைகள்",
    joinNow: "இப்போது சேரவும்",
    freeDelivery2: "இலவச டெலிவரி",
    earlyAccess: "விற்பனைக்கு முன்கூட்டிய அணுகல்",
    discountOnAllRice: "அனைத்து அரிசியிலும் தள்ளுபடி",
    riceMartPremium: "ரைஸ் மார்ட் பிரீமியம்",
    "Easy to digest": "எளிதில் ஜீரணமாகும்",
    "Good for daily meals": "தினசரி உணவுக்கு நல்லது",
    "Provides long lasting energy": "நீண்ட கால சக்தி அளிக்கும்",
    "Low fat": "குறைந்த கொழுப்பு",
    "Helps control blood sugar": "இரத்த சர்க்கரையை கட்டுப்படுத்த உதவும்",
    "Rich in fiber": "நார்ச்சத்து நிறைந்தது",
    "Good for heart health": "இதய ஆரோக்கியத்திற்கு நல்லது",
    "Helps digestion": "ஜீரணத்திற்கு உதவும்",
    "Very high antioxidants": "மிக அதிக ஆன்டிஆக்ஸிடன்ட்கள்",
    "Improves immunity": "நோய் எதிர்ப்பு சக்தியை மேம்படுத்தும்",
    "Rich in iron": "இரும்புச்சத்து நிறைந்தது",
    "Increases body strength": "உடல் வலிமையை அதிகரிக்கும்",
    "Good for bones": "எலும்புகளுக்கு நல்லது",
    "Improves stamina": "சகிப்புத்தன்மையை மேம்படுத்தும்",
    "Detoxifies body": "உடலை நச்சுத்தன்மையாக்கும்",
    "Boosts immunity": "நோய் எதிர்ப்பு சக்தியை அதிகரிக்கும்",
    "Improves metabolism": "வளர்சிதை மாற்றத்தை மேம்படுத்தும்",
    "Gluten free": "குளூட்டன் இல்லாதது",
    "Easy digestion": "எளிய ஜீரணம்",
    "Good energy source": "நல்ல சக்தி மூலம்",
    "High fiber": "அதிக நார்ச்சத்து",
    "Helps weight control": "எடை கட்டுப்பாட்டிற்கு உதவும்",
    "Supports gut health": "குடல் ஆரோக்கியத்தை ஆதரிக்கும்",
    "Rich in minerals": "கனிமங்கள் நிறைந்தது",
    "Good for women's health": "பெண்களின் ஆரோக்கியத்திற்கு நல்லது",
    "Strengthens immunity": "நோய் எதிர்ப்பு சக்தியை வலுப்படுத்தும்",
    "Natural antioxidants": "இயற்கை ஆன்டிஆக்ஸிடன்ட்கள்",
    "Aromatic traditional rice": "நறுமணமுள்ள பாரம்பரிய அரிசி",
    "Low glycemic index": "குறைந்த கிளைசெமிக் குறியீடு",
    "Rich in nutrients": "ஊட்டச்சத்துக்கள் நிறைந்தது",
    "High iron content": "அதிக இரும்புச்சத்து",
    "Supports weight loss": "எடை குறைப்பிற்கு உதவும்",
    "Premium Quality": "பிரீமியம் தரம்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    confirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    fullName: "முழு பெயர்",
    signIn: "உள்நுழைவு",
    createAccount: "கணக்கை உருவாக்கவும்",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    dontHaveAccount: "கணக்கு இல்லையா?",
    forgotPassword: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    showPassword: "கடவுச்சொல்லைக் காட்டு",
    hidePassword: "கடவுச்சொல்லை மறை",
    emptyCart: "உங்கள் கார்ட் காலியாக உள்ளது",
    removeFromCart: "கார்ட்டிலிருந்து அகற்று",
    updateQuantity: "அளவை புதுப்பிக்கவும்",
    subtotal: "துணை மொத்தம்",
    productDetails: "பொருள் விவரங்கள்",
    specifications: "விவரக்குறிப்புகள்",
    reviews: "மதிப்புரைகள்",
    relatedProducts: "தொடர்புடைய பொருட்கள்",
    outOfStock: "கையிருப்பில் இல்லை",
    inStock: "கையிருப்பில் உள்ளது",
    orderHistory: "ஆர்டர் வரலாறு",
    orderNumber: "ஆர்டர் எண்",
    orderDate: "ஆர்டர் தேதி",
    orderStatus: "ஆர்டர் நிலை",
    orderTotal: "ஆர்டர் மொத்தம்",
    viewDetails: "விவரங்களைப் பார்க்கவும்",
    contactUs: "எங்களைத் தொடர்பு கொள்ளவும்",
    getInTouch: "தொடர்பில் இருங்கள்",
    address: "முகவரி",
    phone: "தொலைபேசி",
    enterOrderNumber: "ஆர்டர் எண்ணை உள்ளிடவும்",
    trackYourOrder: "உங்கள் ஆர்டரைக் கண்காணிக்கவும்",
    orderNotFound: "ஆர்டர் கிடைக்கவில்லை",
    limitedTimeOffers: "குறிப்பிட்ட கால சலுகைகள்",
    offerExpires: "சலுகை காலாவதியாகிறது",
    orderPlaced: "ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது",
    thankYou: "நன்றி",
    orderConfirmation: "ஆர்டர் உறுதிப்படுத்தல்",
    Traditional: "பாரம்பரிய",
    Premium: "பிரீமியம்",
    Aromatic: "நறுமணம்",
    White: "வெள்ளை",
    Red: "சிவப்பு",
    Black: "கருப்பு",
    Brown: "பழுப்பு",
    "Basmati Rice": "பாஸ்மதி அரிசி",
    "Seeraga Samba Rice": "சீரக சம்பா அரிசி",
    "Karuppu Kavuni Rice": "கருப்பு கவுனி அரிசி",
    "Ponni Rice": "பொன்னி அரிசி",
    "Idly Rice": "இட்லி அரிசி",
    "Mappillai Samba Rice": "மாப்பிள்ளை சம்பா அரிசி",
    "Kattuyanam Rice": "காட்டுயானம் அரிசி",
    "Thooyamalli Rice": "தூயமல்லி அரிசி",
    "Nei Kichadi Rice": "நெய் கிச்சடி அரிசி",
    "Karunguruvai Rice": "கருங்குறுவை அரிசி",
    "Poongar Rice": "பூங்கார் அரிசி",
    "Red Rice": "சிவப்பு அரிசி"
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => translations[language][key] || key;

  const toggleLanguage = () => setLanguage(prev => prev === 'en' ? 'ta' : 'en');

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};
